// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Otterly.Database;

#nullable disable

namespace Otterly.API.Migrations
{
    [DbContext(typeof(OtterlyAppsContext))]
    [Migration("20230606133426_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Otterly.Database.DataObjects.BingoCard", b =>
                {
                    b.Property<int>("CardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CardSize")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FreeSpace")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TitleText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("CardID");

                    b.ToTable("BingoCards");
                });

            modelBuilder.Entity("Otterly.Database.DataObjects.BingoSlot", b =>
                {
                    b.Property<int>("SlotIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CardID")
                        .HasColumnType("int");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SlotIndex");

                    b.ToTable("BingoSlots");
                });

            modelBuilder.Entity("Otterly.Database.DataObjects.OtterlyAppsUser", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Test")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("OtterlyAppsUsers");
                });

            modelBuilder.Entity("Otterly.Database.DataObjects.UserBingoOptions", b =>
                {
                    b.Property<int>("UserIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ActiveBingoCard")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("Payout")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("UserIndex");

                    b.ToTable("UserBingoOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
